### ISSUE TITLE
Eco/Dry/Fan Modes on Midea U Inverter Window AC

### ISSUE THREAD

**Issue by jscanzoni** [ttimpe/homebridge-midea#17]
I grabbed two of these this a month ago and love them: https://www.amazon.com/Midea-Inverter-Conditioner-Flexibility-Installation/dp/B08677DCKN

I just installed homebridge-midea and am impressed. Wondering if there are any plans to implement "dry" and "fan-only" modes. Dry would be especially helpful as I'm thinking of buying a humidity sensor and building some automation around that rather than temperature.

Additionally, I tend to leave my AC in "Eco" mode, but whenever I change the temperature through Homekit it switches to off.

What's the best way to grab a payload from my units/homebridge/mobile app to find those values to incorporate them?

**Comment by ttimpe** [comment]
Hello,

because custom operational modes sadly do not exist yet, this was not yet properly implemented.

I just implemented keeping the ecoMode the way it is and a separate fan-only mode as had been suggested and contributed earlier but was removed by me when doing the TypeScript implementation.

If you want to help out, put your phone behind an HTTP proxy and look at all traffic to and from `https://mapp.appsmb.com`

The payload data can be decrypted using the code in MideaPlatform.ts although I do have separate .ts file locally for de- and encrypting the request and response, which I do plan to make public as soon as it actually works properly.

For now, look in the #development branch for Fan-Only-Mode and the ecoMode fix.

**Comment by adrianopery** [comment]
The plugin is now working for me.
I add the device but nothing happens.
The device still not configured.
I believe some error is occurring.

**Comment by jscanzoni** [comment]
@ttimpe -- I grabbed the fork from July 5 due to async login not working for me in the latest development branch. Since I don't have an HTTP proxy on my network, is there anything currently in or that could be added to the debug logs which would be useful to share with you?

**Comment by ttimpe** [comment]
If there‘s a mismatch between „homebridge-midea“ and „midea“, please manually change the platform name in your config to „midea“

**Comment by adrianopery** [comment]
I changed but still with the same problem...

LOG:
06/07/2020 18:28:57 HOOBS listening on port 8080.
06/07/2020 18:29:00 Loaded plugin "homebridge-camera-ffmpeg".
06/07/2020 18:29:00 Loaded plugin "homebridge-magichome-platform".
06/07/2020 18:29:00 Loaded plugin "homebridge-midea".

Even I changed on Json and restart all, the plugin loaded is the same "homebridge-midea".

Json:
"platform": "midea",
            "plugin_map": {
                "plugin_name": "midea"
            },
            "devices": [
                {
                    "deviceId": "device ID",
                    "supportedSwingMode": "Vertical",
                    "temperatureSteps": 1
                }
            ],
            "user": "My account email",
            "password": "password",
            "interval": 1
        }

**Comment by ttimpe** [comment]
That seems like a valid config. If the plugin still is not loaded, it seems to be a problem of your installation.

**Comment by krszgabor** [comment]
Ive got the same error message "The requested platform "midea" was not registered by any plugin." A simply node, npm and homebridge update solved the problem.

**Comment by ttimpe** [comment]
I can confirm this, working on testing pipeline and a fix right now.

**Comment by ttimpe** [comment]
Fixed with 1.1.1

**Comment by adrianopery** [comment]
My Midea AC is using today a MSmart app on iphone.
How can I do to identify the device ID?

**Comment by ttimpe** [comment]
You don‘t need the deviceId for the plugin to work. Optional settings like the swingMode can be set using the device-specific overrides. The deviceId is presented in the „Serial Number“ field in the Home app.

**Comment by adrianopery** [comment]
ok. But On my Home app my Midea Acs doesn't appears.
I'm not sure if is compatible.

**Comment by ttimpe** [comment]
Exactly which app are you using to control your devices? Midea Air? Nethome Plus?

**Comment by adrianopery** [comment]
I'm using MSmart Midea.

**Comment by adrianopery** [comment]
but anyway, on my iphone I can't see any new device crated by the plugin.
Should I see even the incompatibility?

**Comment by ttimpe** [comment]
If you cannot use Midea Air or Nethome Plus with your account, it is not compatible with this plugin. Try logging in into one of these apps and report back please.

**Comment by bpengu1n** [comment]
https://github.com/andersonshatch/midea-ac-lib/tree/master/midea Wouldn't this lib provide some of that functionality?
